services:
  - type: web
    name: alash-academy
    env: php
    plan: starter
    runtime: php@8.1
    buildCommand: ./build.sh
    startCommand: heroku-php-apache2 public/
    healthCheckPath: /hello.html
    healthCheckTimeout: 20
    autoDeploy: true
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: alash-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: alash-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: alash-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: alash-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: alash-db
          property: password

databases:
  - name: alash-db
    plan: starter